include("${CMAKE_CURRENT_LIST_DIR}/mpi-cpp-fortran-targets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../BLTOptions.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../BLTPrivateMacros.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../BLTMacros.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../SetupMPI.cmake")